// This enum was generated by Easer
//	Do not modify this file, it will be overwritten by Easer.
public enum EaserEase{
	InSine = 0,
	OutSine = 1,
	InOutSine = 2,
	InBack = 3,
	OutBack = 4,
	InOutBack = 5,
	InCubic = 6,
	OutCubic = 7,
	InOutCubic = 8,
	InElastic = 9,
	OutElastic = 10,
	InOutElastic = 11,
	InBounce = 12,
	OutBounce = 13,
	InOutBounce = 14,
	CustomCurve = 15,
}
